development:
  adapter: postgresql
  encoding: utf8
  database: find-waldo_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: find-waldo_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: find-waldo_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST